### ISSUE TITLE
ImportError: No module named fcntl

### ISSUE THREAD

**Issue by Sec4Fun** [aprilahijriyan/w3brute#1]
While running on windows 7 machine, its throwing following error.

Traceback (most recent call last):
  File "w3brute.py", line 24, in <module>
    import fcntl
ImportError: No module named fcntl

**Comment by aprilahijriyan** [comment]
@Sec4Fun  it seems that the fcntl module is only available on the linux platform. see here: https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows .
